[mgr]
cwd = { fg = "#9eabac", italic = true }

# Hovered
hovered = { bg = "#063540" }
preview_hovered = { bg = "#063540" }

# Find
find_keyword = { fg = "#001419", bg = "#268bd3", bold = true }
find_position = { fg = "#268bd3", bg = "#063540", bold = true }

# Marker
marker_copied = { fg = "#d23681", bg = "#d23681" }
marker_cut = { fg = "#db302d", bg = "#db302d" }
marker_marked = { fg = "#268bd3", bg = "#268bd3" }
marker_selected = { fg = "#001419", bg = "#268bd3" }

# Tab
tab_active = { fg = "#9eabac", bg = "#063540" }
tab_inactive = { fg = "#576d74", bg = "#001419" }
tab_width = 1

# Count
count_copied = { fg = "#9eabac", bg = "#d23681" }
count_cut = { fg = "#9eabac", bg = "#db302d" }
count_selected = { fg = "#9eabac", bg = "#063540" }

# Border
border_symbol = "â”‚"
border_style = { fg = "#063540" }

[status]
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }

progress_label = { fg = "#9eabac", bold = true }
progress_normal = { fg = "#001419" }
progress_error = { fg = "#db302d" }

# Permissions
permissions_t = { fg = "#268bd3" }
permissions_r = { fg = "#566769" }
permissions_w = { fg = "#667678" }
permissions_x = { fg = "#d23681" }
permissions_s = { fg = "#576d74" }

[mode]
normal_main = { fg = "#001419", bg = "#268bd3", bold = true }
normal_alt = { fg = "#9eabac", bg = "#576d74" }

select_main = { fg = "#001419", bg = "#d23681", bold = true }
select_alt = { fg = "#9eabac", bg = "#576d74" }

unset_main = { fg = "#001419", bg = "#db302d", bold = true }
unset_alt = { fg = "#9eabac", bg = "#576d74" }

[select]
border = { fg = "#268bd3" }
active = { fg = "#9eabac", bg = "#063540" }
inactive = { fg = "#9eabac" }

[input]
border = { fg = "#268bd3" }
title = {}
value = { fg = "#268bd3" }
selected = { bg = "#063540" }

[completion]
border = { fg = "#268bd3" }
active = { fg = "#9eabac", bg = "#063540" }
inactive = { fg = "#9eabac" }

[tasks]
border = { fg = "#268bd3" }
title = {}
hovered = { fg = "#9eabac", bg = "#063540" }

[which]
cols = 3
mask = { bg = "#001419" }
cand = { fg = "#268bd3" }
rest = { fg = "#566769" }
desc = { fg = "#667678" }
separator = "  "
separator_style = { fg = "#576d74" }

[notify]
title_info = { fg = "#268bd3" }
title_warn = { fg = "#566769" }
title_error = { fg = "#db302d" }

[help]
on = { fg = "#d23681" }
run = { fg = "#268bd3" }
hovered = { bg = "#063540" }
footer = { fg = "#9eabac", bg = "#001419" }

[filetype]
rules = [
  # Media
  { mime = "{audio,video,image}/*", fg = "#d23681" },

  # Archives
  { mime = "application/*zip", fg = "#db302d" },
  { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#db302d" },

  # Documents
  { mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#268bd3" },

  # Special files
  { name = "*", is = "link", fg = "#667678" },
  { name = "*/", is = "link", fg = "#667678" },
  { name = "*", is = "orphan", bg = "#db302d" },
  { name = "*", is = "exec", fg = "#d23681" },

  # Fallback
  { name = "*/", fg = "#9eabac" },
]
