[mgr]
cwd = { fg = "#d4be98", italic = true }

# Hovered
hovered = { bg = "#282828" }
preview_hovered = { bg = "#282828" }

# Find
find_keyword = { fg = "#1d2021", bg = "#7daea3", bold = true }
find_position = { fg = "#7daea3", bg = "#282828", bold = true }

# Marker
marker_copied = { fg = "#d3869b", bg = "#d3869b" }
marker_cut = { fg = "#ea6962", bg = "#ea6962" }
marker_marked = { fg = "#7daea3", bg = "#7daea3" }
marker_selected = { fg = "#1d2021", bg = "#7daea3" }

# Tab
tab_active = { fg = "#d4be98", bg = "#282828" }
tab_inactive = { fg = "#928374", bg = "#1d2021" }
tab_width = 1

# Count
count_copied = { fg = "#d4be98", bg = "#d3869b" }
count_cut = { fg = "#d4be98", bg = "#ea6962" }
count_selected = { fg = "#d4be98", bg = "#282828" }

# Border
border_symbol = "â”‚"
border_style = { fg = "#282828" }

[status]
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }

progress_label = { fg = "#d4be98", bold = true }
progress_normal = { fg = "#1d2021" }
progress_error = { fg = "#ea6962" }

# Permissions
permissions_t = { fg = "#7daea3" }
permissions_r = { fg = "#817662" }
permissions_w = { fg = "#93866e" }
permissions_x = { fg = "#d3869b" }
permissions_s = { fg = "#928374" }

[mode]
normal_main = { fg = "#1d2021", bg = "#7daea3", bold = true }
normal_alt = { fg = "#d4be98", bg = "#928374" }

select_main = { fg = "#1d2021", bg = "#d3869b", bold = true }
select_alt = { fg = "#d4be98", bg = "#928374" }

unset_main = { fg = "#1d2021", bg = "#ea6962", bold = true }
unset_alt = { fg = "#d4be98", bg = "#928374" }

[select]
border = { fg = "#7daea3" }
active = { fg = "#d4be98", bg = "#282828" }
inactive = { fg = "#d4be98" }

[input]
border = { fg = "#7daea3" }
title = {}
value = { fg = "#7daea3" }
selected = { bg = "#282828" }

[completion]
border = { fg = "#7daea3" }
active = { fg = "#d4be98", bg = "#282828" }
inactive = { fg = "#d4be98" }

[tasks]
border = { fg = "#7daea3" }
title = {}
hovered = { fg = "#d4be98", bg = "#282828" }

[which]
cols = 3
mask = { bg = "#1d2021" }
cand = { fg = "#7daea3" }
rest = { fg = "#817662" }
desc = { fg = "#93866e" }
separator = "  "
separator_style = { fg = "#928374" }

[notify]
title_info = { fg = "#7daea3" }
title_warn = { fg = "#817662" }
title_error = { fg = "#ea6962" }

[help]
on = { fg = "#d3869b" }
run = { fg = "#7daea3" }
hovered = { bg = "#282828" }
footer = { fg = "#d4be98", bg = "#1d2021" }

[filetype]
rules = [
  # Media
  { mime = "{audio,video,image}/*", fg = "#d3869b" },

  # Archives
  { mime = "application/*zip", fg = "#ea6962" },
  { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#ea6962" },

  # Documents
  { mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#7daea3" },

  # Special files
  { name = "*", is = "link", fg = "#93866e" },
  { name = "*/", is = "link", fg = "#93866e" },
  { name = "*", is = "orphan", bg = "#ea6962" },
  { name = "*", is = "exec", fg = "#d3869b" },

  # Fallback
  { name = "*/", fg = "#d4be98" },
]
